/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestorcomponentes;

/**
 *
 * @author barra
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtTipo = new javax.swing.ButtonGroup();
        rbtClasificación = new javax.swing.ButtonGroup();
        rbtTipoRecursos = new javax.swing.ButtonGroup();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblDevelopers = new javax.swing.JLabel();
        lblNombreComponente = new javax.swing.JLabel();
        txfNombreComponente = new javax.swing.JTextField();
        lblTipoComponente = new javax.swing.JLabel();
        rbtOpcion1 = new javax.swing.JRadioButton();
        rbtOpcion2 = new javax.swing.JRadioButton();
        rbtOpcion3 = new javax.swing.JRadioButton();
        rbtOpcion4 = new javax.swing.JRadioButton();
        rbtOpcion5 = new javax.swing.JRadioButton();
        rbtOpcion6 = new javax.swing.JRadioButton();
        lblClasificacionComponente = new javax.swing.JLabel();
        rbtDefensa = new javax.swing.JRadioButton();
        rbtZombie = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnCargarArchivo = new javax.swing.JButton();
        lblVida = new javax.swing.JLabel();
        rbtGif = new javax.swing.JRadioButton();
        rbtSprites = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblImagenesTipo1 = new javax.swing.JLabel();
        txfVida = new javax.swing.JTextField();
        lblGolpes = new javax.swing.JLabel();
        txfGolpes = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        txfNivel = new javax.swing.JTextField();
        lblCampos = new javax.swing.JLabel();
        txfCampos = new javax.swing.JTextField();
        lblNivelAparicion = new javax.swing.JLabel();
        txfNivelAparicion = new javax.swing.JTextField();
        btnGuardarComponente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de componentes - The Walking TEC");
        setResizable(false);

        pnlHeader.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("Gestor de componentes - The Walking TEC");

        lblDevelopers.setText("Victor Aymerich y Anthony Barrantes");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDevelopers)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDevelopers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNombreComponente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreComponente.setText("Nombre del componente:");

        txfNombreComponente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTipoComponente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipoComponente.setText("Tipo del componente:");

        rbtTipo.add(rbtOpcion1);
        rbtOpcion1.setSelected(true);
        rbtOpcion1.setText("Opcion1");

        rbtTipo.add(rbtOpcion2);
        rbtOpcion2.setText("Opcion2");

        rbtTipo.add(rbtOpcion3);
        rbtOpcion3.setText("Opcion3");

        rbtTipo.add(rbtOpcion4);
        rbtOpcion4.setText("Opcion4");

        rbtTipo.add(rbtOpcion5);
        rbtOpcion5.setText("Opcion5");

        rbtTipo.add(rbtOpcion6);
        rbtOpcion6.setText("Opcion6");

        lblClasificacionComponente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClasificacionComponente.setText("Clasificación del componente:");

        rbtClasificación.add(rbtDefensa);
        rbtDefensa.setSelected(true);
        rbtDefensa.setText("Defensa");

        rbtClasificación.add(rbtZombie);
        rbtZombie.setText("Zombie");
        rbtZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtZombieActionPerformed(evt);
            }
        });

        btnCargarArchivo.setText("Cargar archivo");

        lblVida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVida.setText("Vida:");

        rbtTipoRecursos.add(rbtGif);
        rbtGif.setSelected(true);
        rbtGif.setText("GIF");
        rbtGif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGifActionPerformed(evt);
            }
        });

        rbtTipoRecursos.add(rbtSprites);
        rbtSprites.setText("Sprites");
        rbtSprites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSpritesActionPerformed(evt);
            }
        });

        jLabel1.setText("Será invisible y despliega el path o carpeta");

        lblImagenesTipo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblImagenesTipo1.setText("Tipo de recursos:");

        txfVida.setText("0");

        lblGolpes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGolpes.setText("Golpes por unidad de tiempo:");

        txfGolpes.setText("0");

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNivel.setText("Nivel:");

        txfNivel.setText("0");

        lblCampos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCampos.setText("Campos");

        txfCampos.setText("0");

        lblNivelAparicion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNivelAparicion.setText("Nivel de aparición:");

        txfNivelAparicion.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(279, 279, 279)
                            .addComponent(rbtGif)
                            .addGap(111, 111, 111)
                            .addComponent(rbtSprites)
                            .addGap(86, 86, 86)
                            .addComponent(btnCargarArchivo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGolpes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfGolpes, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblNivelAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfNivelAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblImagenesTipo1)
                    .addContainerGap(557, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtGif)
                    .addComponent(rbtSprites)
                    .addComponent(btnCargarArchivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVida)
                    .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGolpes)
                    .addComponent(txfGolpes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivel)
                    .addComponent(txfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampos)
                    .addComponent(txfCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelAparicion)
                    .addComponent(txfNivelAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblImagenesTipo1)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        btnCargarArchivo.getAccessibleContext().setAccessibleDescription("");

        btnGuardarComponente.setText("Guardar Componente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtOpcion2)
                            .addComponent(rbtOpcion1))
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtOpcion3)
                            .addComponent(rbtOpcion4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtOpcion6)
                            .addComponent(rbtOpcion5))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreComponente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfNombreComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTipoComponente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblClasificacionComponente)
                                        .addGap(44, 44, 44)
                                        .addComponent(rbtDefensa)
                                        .addGap(80, 80, 80)
                                        .addComponent(rbtZombie)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnGuardarComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreComponente)
                    .addComponent(txfNombreComponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasificacionComponente)
                    .addComponent(rbtDefensa)
                    .addComponent(rbtZombie))
                .addGap(26, 26, 26)
                .addComponent(lblTipoComponente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtOpcion1)
                        .addComponent(rbtOpcion3))
                    .addComponent(rbtOpcion5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtOpcion2)
                        .addComponent(rbtOpcion4))
                    .addComponent(rbtOpcion6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarComponente)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtZombieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtZombieActionPerformed

    private void rbtSpritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSpritesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtSpritesActionPerformed

    private void rbtGifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtGifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnGuardarComponente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCampos;
    private javax.swing.JLabel lblClasificacionComponente;
    private javax.swing.JLabel lblDevelopers;
    private javax.swing.JLabel lblGolpes;
    private javax.swing.JLabel lblImagenesTipo1;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivelAparicion;
    private javax.swing.JLabel lblNombreComponente;
    private javax.swing.JLabel lblTipoComponente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVida;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.ButtonGroup rbtClasificación;
    private javax.swing.JRadioButton rbtDefensa;
    private javax.swing.JRadioButton rbtGif;
    private javax.swing.JRadioButton rbtOpcion1;
    private javax.swing.JRadioButton rbtOpcion2;
    private javax.swing.JRadioButton rbtOpcion3;
    private javax.swing.JRadioButton rbtOpcion4;
    private javax.swing.JRadioButton rbtOpcion5;
    private javax.swing.JRadioButton rbtOpcion6;
    private javax.swing.JRadioButton rbtSprites;
    private javax.swing.ButtonGroup rbtTipo;
    private javax.swing.ButtonGroup rbtTipoRecursos;
    private javax.swing.JRadioButton rbtZombie;
    private javax.swing.JTextField txfCampos;
    private javax.swing.JTextField txfGolpes;
    private javax.swing.JTextField txfNivel;
    private javax.swing.JTextField txfNivelAparicion;
    private javax.swing.JTextField txfNombreComponente;
    private javax.swing.JTextField txfVida;
    // End of variables declaration//GEN-END:variables
}
